### ISSUE TITLE
check-aws-cloudwatch-logs doesn't create state file

### ISSUE THREAD

**Issue by pussade** [mackerelio/go-check-plugins#281]
Hello.

I use mackerel-check-plugins with v0.28.0.
My agent setting like this:
```
[plugin.checks.logtest]
command = ["check-log", "--file", "/var/log/messages", "--return", "--pattern" "local1.err"]
check_interval = 1

[plugin.checks.cloudlogtest]
command = ["check-aws-cloudwatch-logs", "--log-group-name", "test", "--log-stream-name-prefix", "test", "--pattern", "error", "--critical-over", "0", "--return"]
env = { AWS_REGION = "ap-northeast-1", "AWS_ACCESS_KEY_ID"="************", "AWS_SECRET_ACCESS_KEY"="************" }
check_interval = 1
```

Check-log plugin create state file on /var/tmp/mackerel-agent/check-log but check-aws-cloudwatch-logs does not created anywhere.

What is wrong?

**Comment by lufia** [comment]
I read the source code.

**check-aws-cloudwatch-logs** plugin puts state file only if too many events found in `log-group-name` . Your case might be this.

State file will create a state file in **(workdir)/check-cloudwatch-logs** directory. `(workdir)` is:

if `--state-dir` option is passed, then agent uses this.
if MACKEREL_PLUGIN_WORKDIR is set, then agent uses **$MACKEREL_PLUGIN_WORKDIR**.
if TMPDIR is set, then agent uses **$TMPDIR**.
otherwise agent uses default temporary path such as **/tmp**.

**Comment by pussade** [comment]
Thanks for your answer.
I understand.

**Comment by lufia** [comment]
@pussade Have you more questions on this issue?

**Comment by pussade** [comment]
Sorry. I forgot to close.
