### ISSUE TITLE
Plugins give permission errors if run as non-root user

### ISSUE THREAD

**Issue by n1trux** [mackerelio/go-check-plugins#288]
On my Fedora 29 server, when I run `go-check-plugins disk`, it gives me:

    Disk UNKNOWN: Failed to fetch disk usage: permission denied

If I do the following, it works:

    go-check-plugins disk -X overlay -X tmpfs

And if I run `go-check-plugins ping -H google.com` as regular user, I get

    Ping CRITICAL: listen ip4:icmp : socket: operation not permitted

Even though a regular `ping google.com` works.

I expect the scriptst not to fail in this way when run as a non-root user.

**Comment by hayajo** [comment]
Hello.

`go-check-plugins ping` does an ICMP ping, which handles RAW sockets.

Regular Users can't handle RAW sockets because they don't have the CAP_NET_RAW capability.

`ping` command can be handled as a RAW socket because it runs as the root user with setuid-root or is set the CAP_NET_RAW capability.

To execute `go-check-plugins ping` as a regular user, set setuid-root or set CAP_NET_RAW capability to `go-check-plugins`.

```console
sudo chown root.root /PATH/TO/go-check-plugins
sudo chmod u+s /PATH/TO/go-check-plugins
```

```
sudo setcap CAP_NET_RAW+ep /PATH/TO/go-check-plugins
```

Please see [here](http://man7.org/linux/man-pages/man8/setcap.8.html) for setcap(8).

**Comment by n1trux** [comment]
Thank you for your answer, it's very detailed. I think I didn't exactly formulate my request clearly – I know why it's doing this, but maybe it shouldn't be doing this.

I think if you check for the privileges first you could circumvent the error; e.g. only list the file systems where the user has permissions to see the information (throw a warning/information for non-accessible ones); same with `ping` – if the `go-check-plugins` binary doesn't have permissions, it could wrap the system's `ping` and use that one.

The question is: do you want your users to `setcap CAP_NET_RAW` or do you want the script to work even without the permissions?

Sorry I don't have the time at the moment, I'd have tried to create a PR. Maybe next month…

**Comment by hayajo** [comment]
I see.
I understand that the solution I suggested is not correct.

We will seek out a solution, but we are also waiting for your pull request.

Thank you.

**Comment by hayajo** [comment]
For now, let me close this issue.
Waiting for your p-r.

Thank you.
